package com.easybase.forge.service.generator.service;

import java.nio.file.Path;
import java.util.List;
import java.util.Optional;

import javax.lang.model.element.Modifier;

import com.easybase.forge.common.io.GeneratedArtifact;
import com.easybase.forge.common.util.PackageUtils;
import com.easybase.forge.service.config.CrudOptions;
import com.easybase.forge.service.config.ServiceConfig;
import com.easybase.forge.service.generator.ServiceArtifactGenerator;
import com.easybase.forge.service.generator.ServiceArtifactType;
import com.easybase.forge.service.generator.ServiceMetaUtils;
import com.easybase.forge.service.generator.ServiceNamingUtils;
import com.easybase.forge.service.generator.ServicePackageUtils;
import com.easybase.forge.service.generator.ServiceTypeResolver;
import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

public class LocalServiceBaseImplGenerator implements ServiceArtifactGenerator {

	@Override
	public List<GeneratedArtifact> generate(ServiceConfig config) {
		String pkg = ServicePackageUtils.serviceBasePackage(config);
		String localBaseImplName = ServiceNamingUtils.localServiceBaseImplName(config);
		String localServiceBaseName = ServiceNamingUtils.localServiceBaseName(config);
		String entityName = ServiceNamingUtils.entityName(config);
		String modelPkg = ServicePackageUtils.domainModelPackage(config);
		String repoPkg = ServicePackageUtils.repositoryPackage(config);
		String repoName = ServiceNamingUtils.repositoryName(config);
		String repoFieldName = ServiceNamingUtils.fieldName(config, "Repository");

		ClassName entityType = ClassName.get(modelPkg, entityName);
		ClassName localServiceBaseType = ClassName.get(pkg, localServiceBaseName);
		ClassName repoType = ClassName.get(repoPkg, repoName);

		TypeSpec.Builder builder = TypeSpec.classBuilder(localBaseImplName)
				.addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
				.addSuperinterface(localServiceBaseType)
				.addJavadoc(
						"Abstract local service base implementation for {@code $L}.\n\n"
								+ "<p>Owns the repository reference and provides CRUD implementations. "
								+ "Do not edit this file — it is always regenerated.\n\n"
								+ "<p>Hooks are invoked in {@code $LPersistenceAdapterBase}, not here.\n",
						entityName,
						entityName);

		builder.addField(FieldSpec.builder(repoType, repoFieldName, Modifier.PROTECTED, Modifier.FINAL)
				.build());
		builder.addMethod(buildConstructor(repoType, repoFieldName));
		addCrudMethods(builder, config, entityType, repoFieldName);
		ServiceMetaUtils.applyAuthors(builder, config);

		JavaFile javaFile =
				JavaFile.builder(pkg, builder.build()).skipJavaLangImports(true).build();
		Path outputPath = PackageUtils.packageToPath(config.getResolvedOutputDirectory(), pkg)
				.resolve(localBaseImplName + ".java");

		return List.of(new GeneratedArtifact(
				outputPath, ServiceArtifactType.SERVICE_LOCAL_SERVICE_BASE_IMPL, javaFile.toString()));
	}

	private MethodSpec buildConstructor(ClassName repoType, String repoFieldName) {
		return MethodSpec.constructorBuilder()
				.addModifiers(Modifier.PROTECTED)
				.addParameter(repoType, repoFieldName)
				.addStatement("this.$L = $L", repoFieldName, repoFieldName)
				.build();
	}

	private void addCrudMethods(
			TypeSpec.Builder builder, ServiceConfig config, ClassName entityType, String repoFieldName) {
		CrudOptions crud = config.getCrud();

		if (crud.isCreate()) builder.addMethod(buildCreateMethod(entityType, repoFieldName));
		if (crud.isUpdate()) builder.addMethod(buildUpdateMethod(config, entityType, repoFieldName));
		if (crud.isDelete()) builder.addMethod(buildDeleteMethod(config, repoFieldName));
		if (crud.isGet()) builder.addMethod(buildFindByIdMethod(config, entityType, repoFieldName));
		if (crud.isList()) builder.addMethod(buildFindAllMethod(entityType, repoFieldName));
	}

	private MethodSpec buildCreateMethod(ClassName entityType, String repoFieldName) {
		return MethodSpec.methodBuilder("create")
				.addAnnotation(Override.class)
				.addAnnotation(transactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(entityType, "entity")
				.returns(entityType)
				.addStatement("return $L.create(entity)", repoFieldName)
				.build();
	}

	private MethodSpec buildUpdateMethod(ServiceConfig config, ClassName entityType, String repoFieldName) {
		TypeName idType = ServiceTypeResolver.resolveIdType(config);

		return MethodSpec.methodBuilder("update")
				.addAnnotation(Override.class)
				.addAnnotation(transactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(idType, "id")
				.addParameter(entityType, "entity")
				.returns(entityType)
				.addStatement("return $L.update(id, entity)", repoFieldName)
				.build();
	}

	private MethodSpec buildDeleteMethod(ServiceConfig config, String repoFieldName) {
		TypeName idType = ServiceTypeResolver.resolveIdType(config);

		return MethodSpec.methodBuilder("delete")
				.addAnnotation(Override.class)
				.addAnnotation(transactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(idType, "id")
				.addStatement("$L.deleteById(id)", repoFieldName)
				.build();
	}

	private MethodSpec buildFindByIdMethod(ServiceConfig config, ClassName entityType, String repoFieldName) {
		TypeName idType = ServiceTypeResolver.resolveIdType(config);
		ParameterizedTypeName returnType = ParameterizedTypeName.get(ClassName.get(Optional.class), entityType);

		return MethodSpec.methodBuilder("findById")
				.addAnnotation(Override.class)
				.addAnnotation(readOnlyTransactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(idType, "id")
				.returns(returnType)
				.addStatement("return $L.findById(id)", repoFieldName)
				.build();
	}

	private MethodSpec buildFindAllMethod(ClassName entityType, String repoFieldName) {
		ParameterizedTypeName returnType = ParameterizedTypeName.get(ClassName.get(List.class), entityType);

		return MethodSpec.methodBuilder("findAll")
				.addAnnotation(Override.class)
				.addAnnotation(readOnlyTransactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.returns(returnType)
				.addStatement("return $L.findAll()", repoFieldName)
				.build();
	}

	private AnnotationSpec transactionalAnnotation() {
		return AnnotationSpec.builder(ClassName.get("org.springframework.transaction.annotation", "Transactional"))
				.build();
	}

	private AnnotationSpec readOnlyTransactionalAnnotation() {
		return AnnotationSpec.builder(ClassName.get("org.springframework.transaction.annotation", "Transactional"))
				.addMember("readOnly", "true")
				.build();
	}
}
