package com.example.bookstore.author.service.base;

import com.example.bookstore.author.domain.model.Author;
import com.example.bookstore.author.infrastructure.repository.AuthorRepository;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract local service base implementation for {@code Author}.
 *
 * <p>Owns the repository reference and provides CRUD implementations. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code AuthorPersistenceAdapterBase}, not here.
 */
public abstract class AuthorLocalServiceBaseImpl implements AuthorLocalServiceBase {
  protected final AuthorRepository authorRepository;

  protected AuthorLocalServiceBaseImpl(AuthorRepository authorRepository) {
    this.authorRepository = authorRepository;
  }

  @Override
  @Transactional
  public Author create(Author entity) {
    return authorRepository.create(entity);
  }

  @Override
  @Transactional
  public Author update(UUID id, Author entity) {
    return authorRepository.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(UUID id) {
    authorRepository.deleteById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Author> findById(UUID id) {
    return authorRepository.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Author> findAll() {
    return authorRepository.findAll();
  }
}
