package com.example.bookstore.author.service.base;

import com.example.bookstore.author.domain.model.Author;
import com.example.bookstore.author.service.AuthorLocalService;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract base service implementation for {@code Author}.
 *
 * <p>Delegates all CRUD operations to {@code AuthorLocalService}. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code AuthorPersistenceAdapterBase}, not here.
 */
public abstract class AuthorServiceBaseImpl implements AuthorServiceBase {
  protected final AuthorLocalService authorLocalService;

  protected AuthorServiceBaseImpl(AuthorLocalService authorLocalService) {
    this.authorLocalService = authorLocalService;
  }

  @Override
  @Transactional
  public Author create(Author entity) {
    return authorLocalService.create(entity);
  }

  @Override
  @Transactional
  public Author update(UUID id, Author entity) {
    return authorLocalService.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(UUID id) {
    authorLocalService.delete(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Author> findById(UUID id) {
    return authorLocalService.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Author> findAll() {
    return authorLocalService.findAll();
  }
}
