package com.easybase.forge.service.generator;

import java.nio.file.Path;
import java.util.List;
import java.util.Optional;

import javax.lang.model.element.Modifier;

import com.easybase.forge.common.io.GeneratedArtifact;
import com.easybase.forge.common.util.PackageUtils;
import com.easybase.forge.service.config.CrudOptions;
import com.easybase.forge.service.config.ServiceConfig;
import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

public class ServiceBaseImplGenerator implements ServiceArtifactGenerator {

	@Override
	public List<GeneratedArtifact> generate(ServiceConfig config) {
		String pkg = ServicePackageUtils.serviceBasePackage(config);
		String baseImplName = ServiceNamingUtils.serviceBaseImplName(config);
		String serviceBaseName = ServiceNamingUtils.serviceBaseName(config);
		String localServiceName = ServiceNamingUtils.localServiceName(config);
		String localServicePkg = ServicePackageUtils.servicePackage(config);
		String entityName = ServiceNamingUtils.entityName(config);
		String modelPkg = ServicePackageUtils.domainModelPackage(config);
		String localServiceFieldName = ServiceNamingUtils.fieldName(config, "LocalService");

		ClassName entityType = ClassName.get(modelPkg, entityName);
		ClassName serviceBaseType = ClassName.get(pkg, serviceBaseName);
		ClassName localServiceType = ClassName.get(localServicePkg, localServiceName);

		TypeSpec.Builder builder = TypeSpec.classBuilder(baseImplName)
				.addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
				.addSuperinterface(serviceBaseType)
				.addJavadoc(
						"Abstract base service implementation for {@code $L}.\n\n"
								+ "<p>Delegates all CRUD operations to {@code $LLocalService}. "
								+ "Do not edit this file — it is always regenerated.\n\n"
								+ "<p>Hooks are invoked in {@code $LPersistenceAdapterBase}, not here.\n",
						entityName,
						entityName,
						entityName);

		builder.addField(FieldSpec.builder(localServiceType, localServiceFieldName, Modifier.PROTECTED, Modifier.FINAL)
				.build());
		builder.addMethod(buildConstructor(localServiceType, localServiceFieldName));
		addCrudMethods(builder, config, entityType, localServiceFieldName);

		ServiceMetaUtils.applyAuthors(builder, config);

		JavaFile javaFile =
				JavaFile.builder(pkg, builder.build()).skipJavaLangImports(true).build();
		Path outputPath = PackageUtils.packageToPath(config.getResolvedOutputDirectory(), pkg)
				.resolve(baseImplName + ".java");

		return List.of(
				new GeneratedArtifact(outputPath, ServiceArtifactType.SERVICE_SERVICE_BASE_IMPL, javaFile.toString()));
	}

	private MethodSpec buildConstructor(ClassName localServiceType, String localServiceFieldName) {
		return MethodSpec.constructorBuilder()
				.addModifiers(Modifier.PROTECTED)
				.addParameter(localServiceType, localServiceFieldName)
				.addStatement("this.$L = $L", localServiceFieldName, localServiceFieldName)
				.build();
	}

	private void addCrudMethods(
			TypeSpec.Builder builder, ServiceConfig config, ClassName entityType, String localServiceFieldName) {
		CrudOptions crud = config.getCrud();

		if (crud.isCreate()) builder.addMethod(buildCreateMethod(entityType, localServiceFieldName));
		if (crud.isUpdate()) builder.addMethod(buildUpdateMethod(config, entityType, localServiceFieldName));
		if (crud.isDelete()) builder.addMethod(buildDeleteMethod(config, localServiceFieldName));
		if (crud.isGet()) builder.addMethod(buildFindByIdMethod(config, entityType, localServiceFieldName));
		if (crud.isList()) builder.addMethod(buildFindAllMethod(entityType, localServiceFieldName));
	}

	private MethodSpec buildCreateMethod(ClassName entityType, String localServiceFieldName) {
		return MethodSpec.methodBuilder("create")
				.addAnnotation(Override.class)
				.addAnnotation(transactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(entityType, "entity")
				.returns(entityType)
				.addStatement("return $L.create(entity)", localServiceFieldName)
				.build();
	}

	private MethodSpec buildUpdateMethod(ServiceConfig config, ClassName entityType, String localServiceFieldName) {
		TypeName idType = ServiceTypeResolver.resolveIdType(config);

		return MethodSpec.methodBuilder("update")
				.addAnnotation(Override.class)
				.addAnnotation(transactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(idType, "id")
				.addParameter(entityType, "entity")
				.returns(entityType)
				.addStatement("return $L.update(id, entity)", localServiceFieldName)
				.build();
	}

	private MethodSpec buildDeleteMethod(ServiceConfig config, String localServiceFieldName) {
		TypeName idType = ServiceTypeResolver.resolveIdType(config);

		return MethodSpec.methodBuilder("delete")
				.addAnnotation(Override.class)
				.addAnnotation(transactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(idType, "id")
				.addStatement("$L.delete(id)", localServiceFieldName)
				.build();
	}

	private MethodSpec buildFindByIdMethod(ServiceConfig config, ClassName entityType, String localServiceFieldName) {
		TypeName idType = ServiceTypeResolver.resolveIdType(config);
		ParameterizedTypeName returnType = ParameterizedTypeName.get(ClassName.get(Optional.class), entityType);

		return MethodSpec.methodBuilder("findById")
				.addAnnotation(Override.class)
				.addAnnotation(readOnlyTransactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(idType, "id")
				.returns(returnType)
				.addStatement("return $L.findById(id)", localServiceFieldName)
				.build();
	}

	private MethodSpec buildFindAllMethod(ClassName entityType, String localServiceFieldName) {
		ParameterizedTypeName returnType = ParameterizedTypeName.get(ClassName.get(List.class), entityType);

		return MethodSpec.methodBuilder("findAll")
				.addAnnotation(Override.class)
				.addAnnotation(readOnlyTransactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.returns(returnType)
				.addStatement("return $L.findAll()", localServiceFieldName)
				.build();
	}

	private AnnotationSpec transactionalAnnotation() {
		return AnnotationSpec.builder(ClassName.get("org.springframework.transaction.annotation", "Transactional"))
				.build();
	}

	private AnnotationSpec readOnlyTransactionalAnnotation() {
		return AnnotationSpec.builder(ClassName.get("org.springframework.transaction.annotation", "Transactional"))
				.addMember("readOnly", "true")
				.build();
	}
}
