package com.example.bookstore.book.service.base;

import com.example.bookstore.book.domain.model.Book;
import com.example.bookstore.book.service.BookLocalService;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract base service implementation for {@code Book}.
 *
 * <p>Delegates all CRUD operations to {@code BookLocalService}. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code BookPersistenceAdapterBase}, not here.
 */
public abstract class BookServiceBaseImpl implements BookServiceBase {
  protected final BookLocalService bookLocalService;

  protected BookServiceBaseImpl(BookLocalService bookLocalService) {
    this.bookLocalService = bookLocalService;
  }

  @Override
  @Transactional
  public Book create(Book entity) {
    return bookLocalService.create(entity);
  }

  @Override
  @Transactional
  public Book update(UUID id, Book entity) {
    return bookLocalService.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(UUID id) {
    bookLocalService.delete(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Book> findById(UUID id) {
    return bookLocalService.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Book> findAll() {
    return bookLocalService.findAll();
  }
}
