package com.example.bookstore.book.service.base;

import com.example.bookstore.book.domain.model.Book;
import com.example.bookstore.book.infrastructure.repository.BookRepository;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract local service base implementation for {@code Book}.
 *
 * <p>Owns the repository reference and provides CRUD implementations. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code BookPersistenceAdapterBase}, not here.
 */
public abstract class BookLocalServiceBaseImpl implements BookLocalServiceBase {
  protected final BookRepository bookRepository;

  protected BookLocalServiceBaseImpl(BookRepository bookRepository) {
    this.bookRepository = bookRepository;
  }

  @Override
  @Transactional
  public Book create(Book entity) {
    return bookRepository.create(entity);
  }

  @Override
  @Transactional
  public Book update(UUID id, Book entity) {
    return bookRepository.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(UUID id) {
    bookRepository.deleteById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Book> findById(UUID id) {
    return bookRepository.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Book> findAll() {
    return bookRepository.findAll();
  }
}
