package com.example.petstore.service.base;

import com.example.petstore.domain.model.Owner;
import com.example.petstore.service.OwnerLocalService;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract base service implementation for {@code Owner}.
 *
 * <p>Delegates all CRUD operations to {@code OwnerLocalService}. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code OwnerPersistenceAdapterBase}, not here.
 */
public abstract class OwnerServiceBaseImpl implements OwnerServiceBase {
  protected final OwnerLocalService ownerLocalService;

  protected OwnerServiceBaseImpl(OwnerLocalService ownerLocalService) {
    this.ownerLocalService = ownerLocalService;
  }

  @Override
  @Transactional
  public Owner create(Owner entity) {
    return ownerLocalService.create(entity);
  }

  @Override
  @Transactional
  public Owner update(UUID id, Owner entity) {
    return ownerLocalService.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(UUID id) {
    ownerLocalService.delete(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Owner> findById(UUID id) {
    return ownerLocalService.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Owner> findAll() {
    return ownerLocalService.findAll();
  }
}
