package com.example.petstore.service.base;

import com.example.petstore.domain.model.Owner;
import com.example.petstore.infrastructure.repository.OwnerRepository;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract local service base implementation for {@code Owner}.
 *
 * <p>Owns the repository reference and provides CRUD implementations. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code OwnerPersistenceAdapterBase}, not here.
 */
public abstract class OwnerLocalServiceBaseImpl implements OwnerLocalServiceBase {
  protected final OwnerRepository ownerRepository;

  protected OwnerLocalServiceBaseImpl(OwnerRepository ownerRepository) {
    this.ownerRepository = ownerRepository;
  }

  @Override
  @Transactional
  public Owner create(Owner entity) {
    return ownerRepository.create(entity);
  }

  @Override
  @Transactional
  public Owner update(UUID id, Owner entity) {
    return ownerRepository.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(UUID id) {
    ownerRepository.deleteById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Owner> findById(UUID id) {
    return ownerRepository.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Owner> findAll() {
    return ownerRepository.findAll();
  }
}
