package com.example.petstore.service.base;

import com.example.petstore.domain.model.Pet;
import com.example.petstore.infrastructure.repository.PetRepository;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract local service base implementation for {@code Pet}.
 *
 * <p>Owns the repository reference and provides CRUD implementations. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code PetPersistenceAdapterBase}, not here.
 */
public abstract class PetLocalServiceBaseImpl implements PetLocalServiceBase {
  protected final PetRepository petRepository;

  protected PetLocalServiceBaseImpl(PetRepository petRepository) {
    this.petRepository = petRepository;
  }

  @Override
  @Transactional
  public Pet create(Pet entity) {
    return petRepository.create(entity);
  }

  @Override
  @Transactional
  public Pet update(UUID id, Pet entity) {
    return petRepository.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(UUID id) {
    petRepository.deleteById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Pet> findById(UUID id) {
    return petRepository.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Pet> findAll() {
    return petRepository.findAll();
  }
}
