package com.example.petstore.service.base;

import com.example.petstore.domain.model.Pet;
import com.example.petstore.service.PetLocalService;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract base service implementation for {@code Pet}.
 *
 * <p>Delegates all CRUD operations to {@code PetLocalService}. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code PetPersistenceAdapterBase}, not here.
 */
public abstract class PetServiceBaseImpl implements PetServiceBase {
  protected final PetLocalService petLocalService;

  protected PetServiceBaseImpl(PetLocalService petLocalService) {
    this.petLocalService = petLocalService;
  }

  @Override
  @Transactional
  public Pet create(Pet entity) {
    return petLocalService.create(entity);
  }

  @Override
  @Transactional
  public Pet update(UUID id, Pet entity) {
    return petLocalService.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(UUID id) {
    petLocalService.delete(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Pet> findById(UUID id) {
    return petLocalService.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Pet> findAll() {
    return petLocalService.findAll();
  }
}
