package com.example.petstore.service.base;

import com.example.petstore.domain.model.Vaccination;
import com.example.petstore.infrastructure.repository.VaccinationRepository;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract local service base implementation for {@code Vaccination}.
 *
 * <p>Owns the repository reference and provides CRUD implementations. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code VaccinationPersistenceAdapterBase}, not here.
 */
public abstract class VaccinationLocalServiceBaseImpl implements VaccinationLocalServiceBase {
  protected final VaccinationRepository vaccinationRepository;

  protected VaccinationLocalServiceBaseImpl(VaccinationRepository vaccinationRepository) {
    this.vaccinationRepository = vaccinationRepository;
  }

  @Override
  @Transactional
  public Vaccination create(Vaccination entity) {
    return vaccinationRepository.create(entity);
  }

  @Override
  @Transactional
  public Vaccination update(UUID id, Vaccination entity) {
    return vaccinationRepository.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(UUID id) {
    vaccinationRepository.deleteById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Vaccination> findById(UUID id) {
    return vaccinationRepository.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Vaccination> findAll() {
    return vaccinationRepository.findAll();
  }
}
