package com.example.petstore.service.base;

import com.example.petstore.domain.model.Vaccination;
import com.example.petstore.service.VaccinationLocalService;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract base service implementation for {@code Vaccination}.
 *
 * <p>Delegates all CRUD operations to {@code VaccinationLocalService}. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code VaccinationPersistenceAdapterBase}, not here.
 */
public abstract class VaccinationServiceBaseImpl implements VaccinationServiceBase {
  protected final VaccinationLocalService vaccinationLocalService;

  protected VaccinationServiceBaseImpl(VaccinationLocalService vaccinationLocalService) {
    this.vaccinationLocalService = vaccinationLocalService;
  }

  @Override
  @Transactional
  public Vaccination create(Vaccination entity) {
    return vaccinationLocalService.create(entity);
  }

  @Override
  @Transactional
  public Vaccination update(UUID id, Vaccination entity) {
    return vaccinationLocalService.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(UUID id) {
    vaccinationLocalService.delete(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Vaccination> findById(UUID id) {
    return vaccinationLocalService.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Vaccination> findAll() {
    return vaccinationLocalService.findAll();
  }
}
