package com.easybase.forge.core.config;

/**
 * Project-level audit defaults read from the {@code service.audit} block in
 * {@code easybase-config.yaml}.
 *
 * <p>These values apply to every entity generated by the Service Builder unless
 * overridden in the per-entity {@code easybase.yml}.
 *
 * <p>Example YAML:
 * <pre>
 * service:
 *   audit:
 *     enabled: true
 *     auditorType: UUID
 *     softDelete: true
 *     softDeleteColumn: deleted
 * </pre>
 */
public class AuditDefaults {

	/** Whether audit fields (timestamps + auditor) are generated. Default: {@code true}. */
	private boolean enabled = true;

	/**
	 * Java type for the {@code createdBy} and {@code updatedBy} fields.
	 * Accepted values: {@code UUID}, {@code String}, {@code Long}.
	 * Default: {@code UUID}.
	 */
	private String auditorType = "UUID";

	/** Whether a soft-delete flag replaces hard deletes. Default: {@code false}. */
	private boolean softDelete = false;

	/** Column name used for the soft-delete flag. Default: {@code deleted}. */
	private String softDeleteColumn = "deleted";

	public boolean isEnabled() {
		return enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public String getAuditorType() {
		return auditorType;
	}

	public void setAuditorType(String auditorType) {
		this.auditorType = auditorType;
	}

	public boolean isSoftDelete() {
		return softDelete;
	}

	public void setSoftDelete(boolean softDelete) {
		this.softDelete = softDelete;
	}

	public String getSoftDeleteColumn() {
		return softDeleteColumn;
	}

	public void setSoftDeleteColumn(String softDeleteColumn) {
		this.softDeleteColumn = softDeleteColumn;
	}
}
