basePackage: com.example.petstore

output:
  directory: target/generated-sources/easybase
  layout: MULTI_MODULE

structure:
  controller:
    package: "{basePackage}.{module}.controller"
    basePackage: "{basePackage}.{module}.controller.base"
  delegate:
    package: "{basePackage}.{module}.delegate"
  dto:
    package: "{basePackage}.{module}.dto"

generate:
  delegateImpl: false
  responseEntityWrapping: ALWAYS
  beanValidation: true
  pagination: NONE
