package com.example.bookstore.review.service.base;

import com.example.bookstore.review.domain.model.Review;
import com.example.bookstore.review.infrastructure.repository.ReviewRepository;
import java.util.List;
import java.util.Optional;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract local service base implementation for {@code Review}.
 *
 * <p>Owns the repository reference and provides CRUD implementations. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code ReviewPersistenceAdapterBase}, not here.
 */
public abstract class ReviewLocalServiceBaseImpl implements ReviewLocalServiceBase {
  protected final ReviewRepository reviewRepository;

  protected ReviewLocalServiceBaseImpl(ReviewRepository reviewRepository) {
    this.reviewRepository = reviewRepository;
  }

  @Override
  @Transactional
  public Review create(Review entity) {
    return reviewRepository.create(entity);
  }

  @Override
  @Transactional
  public Review update(Long id, Review entity) {
    return reviewRepository.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(Long id) {
    reviewRepository.deleteById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Review> findById(Long id) {
    return reviewRepository.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Review> findAll() {
    return reviewRepository.findAll();
  }
}
