package com.example.bookstore.review.service.base;

import com.example.bookstore.review.domain.model.Review;
import com.example.bookstore.review.service.ReviewLocalService;
import java.util.List;
import java.util.Optional;
import org.springframework.transaction.annotation.Transactional;

/**
 * Abstract base service implementation for {@code Review}.
 *
 * <p>Delegates all CRUD operations to {@code ReviewLocalService}. Do not edit this file — it is always regenerated.
 *
 * <p>Hooks are invoked in {@code ReviewPersistenceAdapterBase}, not here.
 */
public abstract class ReviewServiceBaseImpl implements ReviewServiceBase {
  protected final ReviewLocalService reviewLocalService;

  protected ReviewServiceBaseImpl(ReviewLocalService reviewLocalService) {
    this.reviewLocalService = reviewLocalService;
  }

  @Override
  @Transactional
  public Review create(Review entity) {
    return reviewLocalService.create(entity);
  }

  @Override
  @Transactional
  public Review update(Long id, Review entity) {
    return reviewLocalService.update(id, entity);
  }

  @Override
  @Transactional
  public void delete(Long id) {
    reviewLocalService.delete(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public Optional<Review> findById(Long id) {
    return reviewLocalService.findById(id);
  }

  @Override
  @Transactional(
      readOnly = true
  )
  public List<Review> findAll() {
    return reviewLocalService.findAll();
  }
}
