plugins {
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management' version '1.1.6'
    id 'java'
    id 'com.easybase.forge.rest' version '0.1.1'
    id 'com.easybase.forge.service' version '0.1.1'
}

group = 'com.example'
version = '1.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    runtimeOnly 'com.h2database:h2'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

easybase {
    specFile = file('src/main/resources/api.yaml')
    configFile = file('easybase-config.yaml')
    outputDirectory = file('src/main/java')
}

easybaseService {
    serviceConfigFile = file('src/main/resources/service.yml')
    projectConfigFile = file('easybase-config.yaml')
    outputDirectory = file('src/main/java')
}

test {
    useJUnitPlatform()
}
