package com.easybase.forge.core.service.generator;

import java.nio.file.Path;
import java.util.List;
import java.util.Optional;

import javax.lang.model.element.Modifier;

import com.easybase.forge.core.generator.GeneratedArtifact;
import com.easybase.forge.core.model.ArtifactType;
import com.easybase.forge.core.service.config.CrudOptions;
import com.easybase.forge.core.service.config.HookOptions;
import com.easybase.forge.core.service.config.ServiceConfig;
import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

/**
 * Generates the abstract base service implementation for the configured entity.
 *
 * <p>This class wires together the repository and hooks, providing the framework-level
 * implementation of all enabled CRUD operations. Developers extend {@code UserServiceImpl}
 * (which extends this class) and add their business methods there.
 *
 * <p>Hook invocation strategy:
 * <ul>
 *   <li>When {@code hook.enabled = true} and {@code hook.multiple = true}:
 *       injects {@code List<UserHook>} and iterates all registered hooks.</li>
 *   <li>When {@code hook.enabled = true} and {@code hook.multiple = false}:
 *       injects a single {@code UserHook} instance.</li>
 *   <li>When {@code hook.enabled = false}: no hook fields or invocations are generated.</li>
 * </ul>
 *
 * <p>All write methods are annotated with {@code @Transactional}.
 * All read methods are annotated with {@code @Transactional(readOnly = true)}.
 *
 * <p>CRUD methods that are disabled in {@code crud:} configuration are omitted entirely.
 */
public class BaseServiceImplGenerator implements ServiceArtifactGenerator {

	@Override
	public List<GeneratedArtifact> generate(ServiceConfig config) {
		String pkg = ServiceGeneratorUtils.baseServicePackage(config);
		String baseImplName = ServiceGeneratorUtils.baseServiceImplName(config);
		String baseServiceName = ServiceGeneratorUtils.baseServiceName(config);
		String repoName = ServiceGeneratorUtils.repositoryName(config);
		String entityName = ServiceGeneratorUtils.entityName(config);
		String modelPkg = ServiceGeneratorUtils.modelPackage(config);
		String repoPkg = ServiceGeneratorUtils.repositoryPackage(config);

		ClassName entityType = ClassName.get(modelPkg, entityName);
		ClassName repoType = ClassName.get(repoPkg, repoName);
		ClassName baseServiceType = ClassName.get(pkg, baseServiceName);

		TypeSpec.Builder builder = TypeSpec.classBuilder(baseImplName)
				.addModifiers(Modifier.PUBLIC, Modifier.ABSTRACT)
				.addSuperinterface(baseServiceType)
				.addAnnotation(AnnotationSpec.builder(ClassName.get("lombok", "RequiredArgsConstructor"))
						.build())
				.addJavadoc(
						"Abstract base service implementation for {@code $L}.\n\n"
								+ "<p>Do not edit this file — it is always regenerated. "
								+ "Extend {@code $LServiceImpl} to add business logic.\n\n"
								+ "<p>All write operations fire the registered hooks before and after persistence.\n",
						entityName,
						entityName);

		builder.addField(FieldSpec.builder(repoType, "repository", Modifier.PROTECTED, Modifier.FINAL)
				.build());

		addHookFields(builder, config);
		addCrudMethods(builder, config, entityType);

		JavaFile javaFile =
				JavaFile.builder(pkg, builder.build()).skipJavaLangImports(true).build();

		Path outputDir = ServiceGeneratorUtils.packageToPath(config.getResolvedOutputDirectory(), pkg);
		Path outputPath = outputDir.resolve(baseImplName + ".java");

		return List.of(new GeneratedArtifact(outputPath, ArtifactType.SERVICE_BASE_SERVICE_IMPL, javaFile.toString()));
	}

	private void addHookFields(TypeSpec.Builder builder, ServiceConfig config) {
		HookOptions hook = config.getHook();

		if (!hook.isEnabled()) {
			return;
		}

		String hookPkg = ServiceGeneratorUtils.hookPackage(config);
		String hookName = ServiceGeneratorUtils.hookName(config);
		ClassName hookType = ClassName.get(hookPkg, hookName);

		if (hook.isMultiple()) {
			ParameterizedTypeName hookListType = ParameterizedTypeName.get(ClassName.get(List.class), hookType);

			builder.addField(FieldSpec.builder(hookListType, "hooks", Modifier.PROTECTED, Modifier.FINAL)
					.build());
		} else {
			builder.addField(FieldSpec.builder(hookType, "hook", Modifier.PROTECTED, Modifier.FINAL)
					.build());
		}
	}

	private void addCrudMethods(TypeSpec.Builder builder, ServiceConfig config, ClassName entityType) {
		CrudOptions crud = config.getCrud();
		ClassName hookType = resolveHookType(config);

		if (crud.isCreate()) {
			builder.addMethod(buildCreateMethod(config, entityType, hookType));
		}

		if (crud.isUpdate()) {
			builder.addMethod(buildUpdateMethod(config, entityType, hookType));
		}

		if (crud.isDelete()) {
			builder.addMethod(buildDeleteMethod(config, hookType));
		}

		if (crud.isGet()) {
			builder.addMethod(buildGetMethod(config, entityType));
		}

		if (crud.isList()) {
			builder.addMethod(buildListMethod(config, entityType));
		}
	}

	private ClassName resolveHookType(ServiceConfig config) {
		return ClassName.get(ServiceGeneratorUtils.hookPackage(config), ServiceGeneratorUtils.hookName(config));
	}

	private MethodSpec buildCreateMethod(ServiceConfig config, ClassName entityType, ClassName hookType) {
		HookOptions hook = config.getHook();

		MethodSpec.Builder builder = MethodSpec.methodBuilder("_create")
				.addAnnotation(Override.class)
				.addAnnotation(transactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(entityType, "entity")
				.returns(entityType);

		if (hook.isEnabled()) {
			addHookCall(builder, hook, hookType, "beforeCreate", "entity");
		}

		builder.addStatement("$T saved = repository.save(entity)", entityType);

		if (hook.isEnabled()) {
			addHookCall(builder, hook, hookType, "afterCreate", "saved");
		}

		builder.addStatement("return saved");

		return builder.build();
	}

	private MethodSpec buildUpdateMethod(ServiceConfig config, ClassName entityType, ClassName hookType) {
		HookOptions hook = config.getHook();
		TypeName idType = ServiceGeneratorUtils.resolveIdType(config);

		MethodSpec.Builder builder = MethodSpec.methodBuilder("_update")
				.addAnnotation(Override.class)
				.addAnnotation(transactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(idType, "id")
				.addParameter(entityType, "entity")
				.returns(entityType);

		if (hook.isEnabled()) {
			addHookCallWithTwoArgs(builder, hook, hookType, "beforeUpdate", "id", "entity");
		}

		builder.addStatement("$T saved = repository.save(entity)", entityType);

		if (hook.isEnabled()) {
			addHookCall(builder, hook, hookType, "afterUpdate", "saved");
		}

		builder.addStatement("return saved");

		return builder.build();
	}

	private MethodSpec buildDeleteMethod(ServiceConfig config, ClassName hookType) {
		HookOptions hook = config.getHook();
		TypeName idType = ServiceGeneratorUtils.resolveIdType(config);

		MethodSpec.Builder builder = MethodSpec.methodBuilder("_delete")
				.addAnnotation(Override.class)
				.addAnnotation(transactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(idType, "id");

		if (hook.isEnabled()) {
			addHookCall(builder, hook, hookType, "beforeDelete", "id");
		}

		builder.addStatement("repository.deleteById(id)");

		if (hook.isEnabled()) {
			addHookCall(builder, hook, hookType, "afterDelete", "id");
		}

		return builder.build();
	}

	private MethodSpec buildGetMethod(ServiceConfig config, ClassName entityType) {
		TypeName idType = ServiceGeneratorUtils.resolveIdType(config);
		ParameterizedTypeName returnType = ParameterizedTypeName.get(ClassName.get(Optional.class), entityType);

		return MethodSpec.methodBuilder("_get")
				.addAnnotation(Override.class)
				.addAnnotation(readOnlyTransactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.addParameter(idType, "id")
				.returns(returnType)
				.addStatement("return repository.findById(id)")
				.build();
	}

	private MethodSpec buildListMethod(ServiceConfig config, ClassName entityType) {
		ParameterizedTypeName returnType = ParameterizedTypeName.get(ClassName.get(List.class), entityType);

		return MethodSpec.methodBuilder("_list")
				.addAnnotation(Override.class)
				.addAnnotation(readOnlyTransactionalAnnotation())
				.addModifiers(Modifier.PUBLIC)
				.returns(returnType)
				.addStatement("return repository.findAll()")
				.build();
	}

	/**
	 * Generates a hook call with a single argument.
	 * Uses {@code for} loop when {@code hook.multiple = true}, direct call otherwise.
	 */
	private void addHookCall(
			MethodSpec.Builder method, HookOptions hook, ClassName hookType, String hookMethod, String arg) {
		if (hook.isMultiple()) {
			method.beginControlFlow("for ($T h : hooks)", hookType);
			method.addStatement("h.$L($L)", hookMethod, arg);
			method.endControlFlow();
		} else {
			method.addStatement("hook.$L($L)", hookMethod, arg);
		}
	}

	/**
	 * Generates a hook call with two arguments (used for {@code beforeUpdate(id, entity)}).
	 */
	private void addHookCallWithTwoArgs(
			MethodSpec.Builder method,
			HookOptions hook,
			ClassName hookType,
			String hookMethod,
			String firstArg,
			String secondArg) {
		if (hook.isMultiple()) {
			method.beginControlFlow("for ($T h : hooks)", hookType);
			method.addStatement("h.$L($L, $L)", hookMethod, firstArg, secondArg);
			method.endControlFlow();
		} else {
			method.addStatement("hook.$L($L, $L)", hookMethod, firstArg, secondArg);
		}
	}

	private AnnotationSpec transactionalAnnotation() {
		return AnnotationSpec.builder(ClassName.get("org.springframework.transaction.annotation", "Transactional"))
				.build();
	}

	private AnnotationSpec readOnlyTransactionalAnnotation() {
		return AnnotationSpec.builder(ClassName.get("org.springframework.transaction.annotation", "Transactional"))
				.addMember("readOnly", "true")
				.build();
	}
}
