package com.easybase.forge.core.service.generator;

import java.nio.file.Path;
import java.util.List;

import javax.lang.model.element.Modifier;

import com.easybase.forge.core.generator.GeneratedArtifact;
import com.easybase.forge.core.model.ArtifactType;
import com.easybase.forge.core.service.config.ServiceConfig;
import com.squareup.javapoet.AnnotationSpec;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;

/**
 * Generates the developer-owned service implementation for the configured entity.
 *
 * <p>The generated class extends {@code UserBaseServiceImpl} (which handles CRUD + hooks)
 * and implements the developer-defined {@code UserService} interface. The constructor is
 * generated by Lombok's {@code @RequiredArgsConstructor}, passing the repository and hooks
 * to the superclass.
 *
 * <p>This file is generated once and <strong>never overwritten</strong> on subsequent runs,
 * preserving any developer additions.
 *
 * <p>Example output for entity {@code User}:
 * <pre>
 * {@literal @}Service
 * {@literal @}RequiredArgsConstructor
 * public class UserServiceImpl extends UserBaseServiceImpl implements UserService {
 *     // Implement methods from UserService here.
 * }
 * </pre>
 */
public class UserServiceImplGenerator implements ServiceArtifactGenerator {

	@Override
	public List<GeneratedArtifact> generate(ServiceConfig config) {
		String pkg = ServiceGeneratorUtils.servicePackage(config);
		String serviceImplName = ServiceGeneratorUtils.serviceImplName(config);
		String serviceName = ServiceGeneratorUtils.serviceName(config);
		String baseImplPkg = ServiceGeneratorUtils.baseServicePackage(config);
		String baseImplName = ServiceGeneratorUtils.baseServiceImplName(config);
		String entityName = ServiceGeneratorUtils.entityName(config);

		ClassName baseImplType = ClassName.get(baseImplPkg, baseImplName);
		ClassName serviceInterface = ClassName.get(pkg, serviceName);

		TypeSpec serviceImpl = TypeSpec.classBuilder(serviceImplName)
				.addModifiers(Modifier.PUBLIC)
				.superclass(baseImplType)
				.addSuperinterface(serviceInterface)
				.addAnnotation(AnnotationSpec.builder(ClassName.get("org.springframework.stereotype", "Service"))
						.build())
				.addAnnotation(AnnotationSpec.builder(ClassName.get("lombok", "RequiredArgsConstructor"))
						.build())
				.addJavadoc(
						"Developer-owned service implementation for {@code $L}.\n\n"
								+ "<p>Implement methods declared in {@link $T} here.\n"
								+ "CRUD operations are inherited from {@code $LBaseServiceImpl}.\n\n"
								+ "<p>This file is generated once and never overwritten.\n",
						entityName,
						serviceInterface,
						entityName)
				.build();

		JavaFile javaFile =
				JavaFile.builder(pkg, serviceImpl).skipJavaLangImports(true).build();

		Path outputDir = ServiceGeneratorUtils.packageToPath(config.getResolvedOutputDirectory(), pkg);
		Path outputPath = outputDir.resolve(serviceImplName + ".java");

		return List.of(new GeneratedArtifact(outputPath, ArtifactType.SERVICE_USER_SERVICE_IMPL, javaFile.toString()));
	}
}
